services:
  claude-code:
    build: 
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - DOCKER_GID=${DOCKER_GID:-10000}
    container_name: claude-code
    volumes:
      - ./home:/home/claude-code
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOME=/home/claude-code
      - NODE_PATH=/home/claude-code/node_modules:/home/claude-install/node_modules
      - PATH=/home/claude-code/node_modules/.bin:/home/claude-install/node_modules/.bin:/home/claude-code/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin