services:
  claude-code:
    build: 
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - DOCKER_GID=${DOCKER_GID:-999}
    container_name: claude-code
    volumes:
      - ./home:/home/claude-code
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOME=/home/claude-code
      
    
    